/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinals3;

import static com.mycompany.proyectofinals3.consultaProfesor.escribirArchivocsv;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author dylan
 */
public class consultaCursos extends javax.swing.JFrame {

    /**
     * Creates new form consultaCursos
     */
    public consultaCursos() {
        initComponents();
        DefaultTableModel data = new DefaultTableModel(new String[]{"id", "Catedratico", "nombre", "seccion", "fechaInicio", "fechaFinal", "horaInicio",
            "horaFinal"}, ProyectoFinalS3.Cursos.size());
        jTable1.setModel(data);
        int row = 0;
        for (Curso a : ProyectoFinalS3.Cursos) {
            jTable1.setValueAt(a.id, row, 0);
            jTable1.setValueAt(a.Catedratico, row, 1);
            jTable1.setValueAt(a.nombre, row, 2);
            jTable1.setValueAt(a.seccion, row, 3);
            jTable1.setValueAt(a.fechai, row, 4);
            jTable1.setValueAt(a.fechaf, row, 5);
            jTable1.setValueAt(a.hora, row, 6);
            jTable1.setValueAt(a.horaf, row, 7);
            row++;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("ImportarJSON");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton3)
                .addGap(140, 140, 140)
                .addComponent(jButton1)
                .addGap(134, 134, 134)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Administrador admin = new Administrador();
        admin.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        editarCurso m = new editarCurso(jTable1.getSelectedRow());
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public  void leerjson(File archivo) {
        System.out.println("obtiene ruta" );
        JSONParser jp = new JSONParser();
        try {
            FileReader r = new FileReader(archivo);
            Object obj = jp.parse(r);
            JSONArray cursoList = (JSONArray) obj;
            System.out.println("lee el archivo");
            for (Object p : cursoList) {
                
                
                
                JSONObject datosCurso = (JSONObject) p;
                
                System.out.println("entra en el ciclor de array");
                long codigo = (long) datosCurso.get("id");

                int id = (int) codigo;

                String nombre = (String) datosCurso.get("nombre");

                String seccion = (String) datosCurso.get("seccion");

                String fechai = (String) datosCurso.get("fecha_inicio");

                String fechaf = (String) datosCurso.get("fecha_fin");

                String catedratico = (String) datosCurso.get("profesor");

//                long ho = (long) datosCurso.get("hora_inicio");
//
//                int hora = (int) ho;
//
//                long hf = (long) datosCurso.get("hora_fin");

//                int horaf = (int)hf;
                System.out.println("entra en json y obtiene dats");
                System.out.println("obtiene datos correctamente");
                
                
                Curso j = new Curso();

                j.nombre = nombre;

                j.seccion = seccion;

                j.fechai = fechai;

                j.fechaf = fechaf;

                j.Catedratico = catedratico;

//                j.hora = hora;
//
//                j.horaf = horaf;

                j.id = id;

                ProyectoFinalS3.Cursos.add(j);

            }
            
            actualizartabla();

        } catch (Exception e) {
            System.out.println(e);
        }

    }

public void actualizartabla(){ 
     DefaultTableModel data = new DefaultTableModel(new String[]{"id", "Catedratico", "nombre", "seccion", "fechaInicio", "fechaFinal", "horaInicio",
            "horaFinal"}, ProyectoFinalS3.Cursos.size());
        jTable1.setModel(data);
        int row = 0;
        for (Curso a : ProyectoFinalS3.Cursos) {
            jTable1.setValueAt(a.id, row, 0);
            jTable1.setValueAt(a.Catedratico, row, 1);
            jTable1.setValueAt(a.nombre, row, 2);
            jTable1.setValueAt(a.seccion, row, 3);
            jTable1.setValueAt(a.fechai, row, 4);
            jTable1.setValueAt(a.fechaf, row, 5);
            jTable1.setValueAt(a.hora, row, 6);
            jTable1.setValueAt(a.horaf, row, 7);
            row++;

        }


    }                                        



    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this,"Cargar");
        if(retorno==JFileChooser.APPROVE_OPTION){
           leerjson(archivo.getSelectedFile());
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
