/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinals3;

import static com.mycompany.proyectofinals3.consultaProfesor.escribirArchivocsv;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

/**
 *
 * @author dylan
 */
public class consultaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form consultaAlumno
     */
    public consultaAlumno() {
        initComponents();
        DefaultTableModel data = new DefaultTableModel(new String[]{"Nombre", "Apellido", "Carne", "Password"},
                ProyectoFinalS3.usuarios.size());
        jTable1.setModel(data);
        int row = 0;
        for (Usuario a : ProyectoFinalS3.usuarios) {
            jTable1.setValueAt(a.getNombre(), row, 0);
            jTable1.setValueAt(a.getApellido(), row, 1);
            jTable1.setValueAt(a.getUsuario(), row, 2);
            jTable1.setValueAt(a.getPassword(), row, 3);

            row++;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consulta Alumnos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Importar CSV");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Importar XML");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Exportar XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton3)
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Administrador admin = new Administrador();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        editarAlumno m = new editarAlumno(jTable1.getSelectedRow());
        m.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed
    public void acturalizarTabal() {

        DefaultTableModel data = new DefaultTableModel(new String[]{"Nombre", "Apellido", "Usuario", "Password"},
                ProyectoFinalS3.usuarios.size());
        jTable1.setModel(data);
        int row = 0;
        for (Usuario a : ProyectoFinalS3.usuarios) {
            jTable1.setValueAt(a.getNombre(), row, 0);
            jTable1.setValueAt(a.getApellido(), row, 1);
            jTable1.setValueAt(a.getUsuario(), row, 2);
            jTable1.setValueAt(a.getPassword(), row, 3);
           

            row++;
        }

    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this, "Cargar");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            leerArchivoTextoAlumno(archivo.getSelectedFile().toPath().toString());
        }

    }//GEN-LAST:event_jButton4ActionPerformed
    public void leerArchivoTextoAlumno(String rutaConNombre) {
        String contenido = "";

        try {
            File f = new File(rutaConNombre);
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String linea = "";
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                Usuario p = new Usuario();
                String uno = datos[0];
                String dos = datos[1];
                String tres = datos[2];
                String cuatro = datos[3];

                p.setNombre(uno);
                p.setApellido(dos);
                p.setUsuario(tres);
                p.setPassword(cuatro);
                ProyectoFinalS3.usuarios.add(p);

            }
            acturalizarTabal();
            fr.close();
            br.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void leerArchivoXMLAlumno(File archivo) {
        // TODO add your handling code here:
        try {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newDefaultInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            Document doc = db.parse(archivo);

            doc.getDocumentElement().normalize();
            NodeList nodos = doc.getElementsByTagName("usuario");
            
            for (int i = 0; i < nodos.getLength(); i++) {
                
                Node nodo = nodos.item(i);
                if (nodo.getNodeType() == Node.ELEMENT_NODE) {

                    Element el = (Element) nodo;
                    Usuario u = new Usuario();

                    u.setNombre(el.getElementsByTagName("nombre").item(0).getTextContent());
                    u.setApellido(el.getElementsByTagName("apellido").item(0).getTextContent());
                    u.setUsuario(el.getElementsByTagName("carnet").item(0).getTextContent());
                    u.setPassword(el.getElementsByTagName("password").item(0).getTextContent());

                    try {
                         ProyectoFinalS3.usuarios.add(u);
  JOptionPane.showMessageDialog(this, "registro agregado al Arraylist" );
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "registro fallo al entrar en Arraylist" );
                    }
             }
            }
            
            
            
            
            
            try {
            
                acturalizarTabal();
            } catch (Exception e) {
               
            }

        } 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "fallo en la carga ");
        }
    }
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this, "Cargar XML");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            leerArchivoXMLAlumno(archivo.getSelectedFile());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String contenido ="<usuarios>\n";
        for(Usuario e: ProyectoFinalS3.usuarios){
     contenido+="\t<usuario>\n";
            contenido+="\t\t<nombre>";
            contenido+=e.getNombre();
            contenido+="</nombre>\n";
            
            
            contenido+="\t\t<codigo>";
            contenido+=e.getApellido();
            contenido+="</codigo>\n";
            
            contenido+="\t\t<usuario>";
            contenido+=e.getUsuario();
            contenido+="</usuario>\n";
            
            contenido+="\t\t<password>";
            contenido+=e.getPassword();
            contenido+="</password>\n";
            
            contenido+="\t</usuario>\n";
        }
        contenido+="</usuarios>";
        
         JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this,"Guardar");
        if(retorno==JFileChooser.APPROVE_OPTION){
           escribirArchivocsv(archivo.getSelectedFile().toPath().toString(),contenido);
           JOptionPane.showMessageDialog(this, "exportacion exitosa");
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
