/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinals3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

/**
 *
 * @author dylan
 */
public class consultaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form consultaProfesor
     */
    public consultaProfesor() {
        initComponents();
        
        
         DefaultTableModel data =new DefaultTableModel( new String[]{"Nombre","Apellido","Usuario","Password"}
                 , ProyectoFinalS3.profesores.size());
        jTable1.setModel(data);
        int row=0;
        for(Profesor a: ProyectoFinalS3.profesores ){
            jTable1.setValueAt(a.nombre, row, 0);
            jTable1.setValueAt(a.apellido, row, 1);
            jTable1.setValueAt(a.usuario, row, 2);
            jTable1.setValueAt(a.password, row, 3);
           // jTable1.setValueAt(a.especialidad, row, 4);
           
           row++;           
    }  
       
        
        
        
    }
    public void acturalizarTabal(){
       
        
        
         DefaultTableModel data =new DefaultTableModel( new String[]{"Nombre","Apellido","Usuario","Password"}
                 , ProyectoFinalS3.profesores.size());
        jTable1.setModel(data);
        int row=0;
        for(Profesor a: ProyectoFinalS3.profesores ){
            jTable1.setValueAt(a.nombre, row, 0);
            jTable1.setValueAt(a.apellido, row, 1);
            jTable1.setValueAt(a.usuario, row, 2);
            jTable1.setValueAt(a.password, row, 3);
           // jTable1.setValueAt(a.especialidad, row, 4);
           
           row++;           
    }  
       
        
        
        
    }
            
            
            
            
            
     public static void escribirArchivocsv(String rutaConNombre, String contenido) {
        try {
         FileWriter fw = new FileWriter(rutaConNombre);
        PrintWriter pw = new PrintWriter(fw);
        pw.write(contenido);
        pw.close();
        fw.close();      
               
         }
           catch(Exception e){
           e.printStackTrace();}
    } 
     
     public void leerArchivoTextoProfesores(String rutaConNombre) {
        String contenido ="";
         
       try {
            File f = new File(rutaConNombre);
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String linea="";
            while((linea = br.readLine())!=null){
                String[] datos =linea.split(",");
                Profesor p = new Profesor();
                p.nombre=datos[0];
                p.apellido=datos[1];
                p.usuario=datos[2];
                p.password=datos[3];
                 ProyectoFinalS3.profesores.add(p);
            
            }
             acturalizarTabal();
            fr.close();
            br.close();
         
         }
           catch(Exception e){
           e.printStackTrace();}
       
       
   
      }
     
    
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Consulta Profesores");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exportar XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Importar CSV");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Importar XML");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exportar CSV");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(107, 107, 107)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addComponent(jButton4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           Administrador admin = new Administrador();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        editarProfesor m = new editarProfesor(jTable1.getSelectedRow());
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
          String contenido ="<profesores>\n";
        for(Profesor e: ProyectoFinalS3.profesores){
     contenido+="\t<profesor>\n";
            contenido+="\t\t<nombre>";
            contenido+=e.nombre;
            contenido+="</nombre>\n";
            
            
            contenido+="\t\t<codigo>";
            contenido+=e.apellido;
            contenido+="</codigo>\n";
            
            contenido+="\t\t<usuario>";
            contenido+=e.usuario;
            contenido+="</usuario>\n";
            
            contenido+="\t\t<password>";
            contenido+=e.password;
            contenido+="</password>\n";
            
            contenido+="\t</profesor>\n";
        }
        contenido+="</profesores>";
        
         JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this,"Guardar");
        if(retorno==JFileChooser.APPROVE_OPTION){
           escribirArchivocsv(archivo.getSelectedFile().toPath().toString(),contenido);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this,"Cargar");
        if(retorno==JFileChooser.APPROVE_OPTION){
           leerArchivoTextoProfesores( archivo.getSelectedFile().toPath().toString());
        }  
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this,"Cargar");
        if(retorno==JFileChooser.APPROVE_OPTION){
           leerArchivoXMLProfesores( archivo.getSelectedFile());
        }  
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String contenido ="";
        for(Profesor e: ProyectoFinalS3.profesores){
     contenido += e.nombre + "," + e.apellido + "," + e.usuario + "," + e.apellido + "\n";
            
        }
        
        
            
        
        
        
        
         JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this,"Guardar");
        if(retorno==JFileChooser.APPROVE_OPTION){
           escribirArchivocsv(archivo.getSelectedFile().toPath().toString(),contenido);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed
public void leerArchivoXMLProfesores (File archivo){                                         
        // TODO add your handling code here:
       try {
           DocumentBuilderFactory dbf = DocumentBuilderFactory.newDefaultInstance();
           DocumentBuilder db = dbf.newDocumentBuilder();
           Document doc = db.parse(archivo);
           
           doc.getDocumentElement().normalize();
           NodeList nodos = doc.getElementsByTagName("profesor");
           for(int i = 0; i<nodos.getLength();i++) {
               Node nodo = nodos.item(i);
               if(nodo.getNodeType() == Node.ELEMENT_NODE){
                   
                   Element e = (Element) nodo;
                   Profesor p = new Profesor();
                   p.nombre = e.getElementsByTagName("nombre").item(0).getTextContent();
                   p.apellido = e.getElementsByTagName("apellido").item(0).getTextContent();
                   p.usuario = e.getElementsByTagName("usuario").item(0).getTextContent();
                   p.password = e.getElementsByTagName("password").item(0).getTextContent();
                   
                   ProyectoFinalS3.profesores.add(p);
                   
               } 
               
               
               
    }
               
        acturalizarTabal();   
           
    } catch (Exception e) {
    }
        }  
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
